# redis configuration
redis:
  db: 0
  addr: '127.0.0.1:6378'
  password: '123456'

# mysql connect configuration
mysql:
  path: '127.0.0.1'
  port: '3306'
  db-name: 'test'
  username: 'root'
  password: '123456'
  max-idle-conns: 10
  max-open-conns: 100
  config: 'charset=utf8mb4&parseTime=True&loc=Local'

system:
  env: 'develop'
  addr: 8888
  db-type: 'mysql'

zap:
  level: 'info'
  format: 'console'
  prefix: '[test]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true